version: '3'
services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+mysqlclient://usuario:contraseña@IP_ELASTICA_AWS/nombre_bd
    command: uvicorn app:app --host 0.0.0.0 --port 8000
